#!/usr/bin/python3
'''
Function raises a named exception with a specific error message.
'''


def raise_exception_msg(message=''):
    raise NameError(message)